### ISSUE TITLE
jobs page - can we make the pitch part wider so we don't have to scroll so much?

### ISSUE THREAD

**Issue by kgueth** [onlylions/suggestions#14]

**Comment by b3ntly** [comment]
Yup, we're going to have it so clicking on a row causes it to slide down for more space - which may be hard to visualize but should fix this issue soon.

**Comment by b3ntly** [comment]
I set the maximum width to 1200 pixels (previously 600), meaning if you increase the width of the page the pitch column will become bigger. It's still shitty but hopefully that makes it less shitty.
